const helper = require('./repository/customhelper');


exports.CreateDataFolders = () => {
    let _data = `${__dirname}/data`;
    let _masters = `${__dirname}/data/masters`;
    let _cabling = `${__dirname}/data/cabling`;
    let _deploy = `${__dirname}/data/deploy`;
    let _equipments = `${__dirname}/data/equipments`;
    let _network = `${__dirname}/data/network`;
    let _pullout = `${__dirname}/data/pullout`;
    let _request = `${__dirname}/data/request`;
    let _transfer = `${__dirname}/data/transfer`;
    let _dploy_cabling = `${__dirname}/data/deploy/cabling`;
    let _deploy_it = `${__dirname}/data/deploy/it`;
    let _masters_access = `${__dirname}/data/masters/access`;
    let _masters_cablingitems = `${__dirname}/data/masters/cablingitems`;
    let _masters_clientname = `${__dirname}/data/masters/clientname`;
    let _masters_clientstores = `${__dirname}/data/masters/clientstores`;
    let _masters_items = `${__dirname}/data/masters/items`;
    let _masters_locations = `${__dirname}/data/masters/locations`;
    let _masters_locationtype = `${__dirname}/data/masters/locationtype`;
    let _masters_personel = `${__dirname}/data/masters/personel`;
    let _masters_positions = `${__dirname}/data/masters/positions`;
    let _masters_users = `${__dirname}/data/masters/users`;
    let _request_cabling = `${__dirname}/data/request/cabling`;
    let _request_equipment = `${__dirname}/data/request/equipment`;
    let _request_stocks = `${__dirname}/data/request/stocks`;
    let _request_transfer = `${__dirname}/data/request/transfer`;
    let _request_cabling_approved = `${__dirname}/data/request/cabling/approved`;
    let _request_cabling_pending = `${__dirname}/data/request/cabling/pending`;
    let _request_cabling_return = `${__dirname}/data/request/cabling/return`;
    let _request_equipment_approved = `${__dirname}/data/request/equipment/approved`;
    let _request_equipment_assigned = `${__dirname}/data/request/equipment/assigned`;
    let _request_equipment_pending = `${__dirname}/data/request/equipment/pending`;
    let _request_equipment_return = `${__dirname}/data/request/equipment/return`;
    let _request_stocks_cabling = `${__dirname}/data/request/equipment/return`;
    let _request_stocks_done = `${__dirname}/data/request/equipment/return`;
    let _request_stocks_it = `${__dirname}/data/request/equipment/return`;
    let _request_transfer_approved = `${__dirname}/data/request/transfer/approved`;
    let _request_transfer_pending = `${__dirname}/data/request/transfer/pending`;
    let _request_transfer_return = `${__dirname}/data/request/transfer/return`;

    helper.CreateFolder(_data);
    helper.CreateFolder(_masters);
    helper.CreateFolder(_cabling);
    helper.CreateFolder(_deploy);
    helper.CreateFolder(_equipments);
    helper.CreateFolder(_network);
    helper.CreateFolder(_pullout);
    helper.CreateFolder(_request);
    helper.CreateFolder(_transfer);
    helper.CreateFolder(_dploy_cabling);
    helper.CreateFolder(_deploy_it);
    helper.CreateFolder(_masters_access);
    helper.CreateFolder(_masters_cablingitems);
    helper.CreateFolder(_masters_clientname);
    helper.CreateFolder(_masters_clientstores);
    helper.CreateFolder(_masters_items);
    helper.CreateFolder(_masters_locations);
    helper.CreateFolder(_masters_locationtype);
    helper.CreateFolder(_masters_personel);
    helper.CreateFolder(_masters_positions);
    helper.CreateFolder(_masters_users);
    helper.CreateFolder(_request_cabling);
    helper.CreateFolder(_request_equipment);
    helper.CreateFolder(_request_stocks);
    helper.CreateFolder(_request_transfer);
    helper.CreateFolder(_request_cabling_approved);
    helper.CreateFolder(_request_cabling_pending);
    helper.CreateFolder(_request_cabling_return);
    helper.CreateFolder(_request_equipment_approved);
    helper.CreateFolder(_request_equipment_assigned);
    helper.CreateFolder(_request_equipment_pending);
    helper.CreateFolder(_request_equipment_return);
    helper.CreateFolder(_request_stocks_cabling);
    helper.CreateFolder(_request_stocks_done);
    helper.CreateFolder(_request_stocks_it);
    helper.CreateFolder(_request_transfer_approved);
    helper.CreateFolder(_request_transfer_pending);
    helper.CreateFolder(_request_transfer_return);
}